version: '3'

services:
  graphite:
    image: "sitespeedio/graphite"
    ports:
      - "8080:80"
      - "2003:2003"

  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    volumes: 
      - ./var/lib/grafana:/var/lib/grafana
    
  cassandra:
    build:
      context: .
      args:
        graphiteprefix: cassandra-node1

  cassandra-init:
    build:
      context: ./init_schema
    depends_on:
      - cassandra
    environment:
      cassandra_node: cassandra
    ports:
      - "9042"
    links:
      - cassandra
    